
-----CLEANED--------
SELECT * FROM DIM_CUSTOMERS;
SELECT * FROM DIM_PRODUCTS;
SELECT * FROM FACT_ORDERS;
SELECT * FROM ITEMS;



SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.ORDER_ID,I.PRODUCT_ID,I.SALES 
FROM 
(SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,O.ORDER_ID FROM DIM_CUSTOMERS C INNER JOIN FACT_ORDERS O ON (C.CUSTOMER_ID=O.CUSTOMER_ID)) C 
INNER JOIN 
ITEMS I ON (C.ORDER_ID=I.ORDER_ID);




SELECT CUSTOMER_ID, CUSTOMER_NAME,SUM(SALES)SUM FROM (
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.ORDER_ID,I.PRODUCT_ID,I.SALES 
FROM 
(SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,O.ORDER_ID FROM DIM_CUSTOMERS C INNER JOIN FACT_ORDERS O ON (C.CUSTOMER_ID=O.CUSTOMER_ID)) C 
INNER JOIN 
ITEMS I ON (C.ORDER_ID=I.ORDER_ID)) GROUP BY CUSTOMER_ID,CUSTOMER_NAME ORDER BY SUM DESC;



_____________________________TOP 10 CUSTOMERS_________________________________________

SELECT CUSTOMER_ID, CUSTOMER_NAME, SUM FROM 
(
    SELECT CUSTOMER_ID, CUSTOMER_NAME, SUM,RANK()OVER(ORDER BY SUM DESC)RN FROM 
        (
        SELECT CUSTOMER_ID, CUSTOMER_NAME,SUM(SALES)SUM FROM
        (
                 SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.ORDER_ID,I.PRODUCT_ID,I.SALES 
                 FROM 
                            (SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,O.ORDER_ID FROM DIM_CUSTOMERS C INNER JOIN FACT_ORDERS O ON (C.CUSTOMER_ID=O.CUSTOMER_ID)) C 
                            INNER JOIN 
                            ITEMS I ON (C.ORDER_ID=I.ORDER_ID))
        GROUP BY CUSTOMER_ID,CUSTOMER_NAME)
                
)
WHERE RN<=10
;
___________________________________________________________________________________________

___________________________________REGION WISE SALES____________________________________________

SELECT REGION,SUM(SALES)SUM_OF_SALES FROM
            (
                SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.REGION,I.SALES 
                           FROM 
                                (SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.REGION, O.ORDER_ID FROM DIM_CUSTOMERS C INNER JOIN FACT_ORDERS O ON (C.CUSTOMER_ID=O.CUSTOMER_ID))C
                                INNER JOIN ITEMS I
                                ON (C.ORDER_ID = I.ORDER_ID)
            )
            GROUP BY REGION;

___________________________________________________________________________________________

__________________________________CATEGORY WISE PROFIT_______________________________________

SELECT CATEGORY,SUM(PROFIT) SUM_OF_PROFIT FROM (
                        SELECT P.PRODUCT_ID,P.CATEGORY, I.PROFIT FROM DIM_PRODUCTS P INNER JOIN ITEMS I ON (P.PRODUCT_ID=I.PRODUCT_ID)
                        )
                        GROUP BY CATEGORY;

_____________________________________________________________________________________________



SELECT TO_CHAR(ORDER_DATE,'MONTH')MONTH FROM FACT_ORDERS;

____________________________________________MONTH WISE SALE________________________________________________

SELECT MONTH, SUM(SALES)SUM_OF_SALES FROM
                        (
                            SELECT TO_CHAR(ORDER_DATE,'MONTH')MONTH,SALES FROM 
                                             (SELECT O.ORDER_ID,O.ORDER_DATE,I.SALES FROM FACT_ORDERS O INNER JOIN ITEMS I ON (O.ORDER_ID=I.ORDER_ID) 
                                             )
                        )GROUP BY MONTH;
                        
                        
_____________________________________CUSTOMER WISE ORDER COUNT__________________________________________________

SELECT CUSTOMER_ID ,COUNT(ORDER_ID)COUNT FROM (SELECT C.CUSTOMER_ID, O.ORDER_ID FROM DIM_CUSTOMERS C INNER JOIN FACT_ORDERS O ON (C.CUSTOMER_ID = O.CUSTOMER_ID))GROUP BY CUSTOMER_ID;


_____________________________________TOP 5 PRODUCTS BY SALE____________________________________________________________

SELECT PRODUCT_NAME,SALES FROM
(
                SELECT PRODUCT_NAME,SALES,RANK()OVER(ORDER BY SALES DESC)RN FROM
                    (
                        SELECT PRODUCT_NAME, SUM(SALES)SALES FROM 
                                                    (SELECT P.PRODUCT_ID,P.PRODUCT_NAME,I.SALES FROM DIM_PRODUCTS P INNER JOIN ITEMS I ON (P.PRODUCT_ID=I.PRODUCT_ID)) 
                         GROUP BY PRODUCT_NAME)
)
WHERE RN<=5;




******************************END TO END DATA VALIDATION*************************************************

------RAW--------
SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;

SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(*) FROM ORDERS;

SELECT COUNT(DISTINCT ORDER_ID) FROM ORDERS;
SELECT COUNT(DISTINCT ORDER_ID) FROM FACT_ORDERS;

SELECT COUNT(*) FROM ITEMS;
SELECT COUNT(*) FROM FACT_ITEMS;
TRUNCATE TABLE FACT_ITEMS;


-----CLEANED--------
SELECT * FROM DIM_CUSTOMERS;
SELECT * FROM DIM_PRODUCTS;
SELECT * FROM FACT_ORDERS;


_________________________DATA VALIDATION_______________________________________________


SELECT COUNT(*) FROM DIM_CUSTOMERS;
SELECT COUNT(*) FROM DIM_PRODUCTS;
SELECT COUNT(*) FROM FACT_ORDERS;
SELECT COUNT(*) FROM FACT_ITEMS;
SELECT * FROM FACT_ITEMS;

SELECT SUM(SALES) SALES,SUM(QUANTITY) QUANTITY, SUM(PROFIT)PROFIT FROM ITEMS;
SELECT SUM(SALES) SALES,SUM(QUANTITY) QUANTITY, SUM(PROFIT)PROFIT FROM FACT_ITEMS;

SELECT ORDER_ID,PRODUCT_ID,COUNT(*) C FROM FACT_ITEMS GROUP BY ORDER_ID,PRODUCT_ID HAVING COUNT(*)>1;
SELECT ORDER_ID,PRODUCT_ID,COUNT(*) C FROM ITEMS GROUP BY ORDER_ID,PRODUCT_ID HAVING COUNT(*)>1;

SELECT COUNT(*) FROM FACT_ITEMS WHERE ORDER_ID IS NULL;
SELECT COUNT(*) FROM FACT_ITEMS WHERE PRODUCT_ID IS NULL;
SELECT COUNT(*) FROM FACT_ITEMS WHERE SALES IS NULL;
SELECT COUNT(*) FROM FACT_ITEMS WHERE QUANTITY IS NULL;
SELECT COUNT(*) FROM FACT_ITEMS WHERE  DISCOUNT IS NULL;
SELECT COUNT(*) FROM FACT_ITEMS WHERE PROFIT IS NULL;


SELECT COUNT(*) FROM FACT_ORDERS WHERE ORDER_ID IS NULL;
SELECT COUNT(*) FROM FACT_ORDERS WHERE ORDER_DATE IS NULL;
SELECT COUNT(*) FROM FACT_ORDERS WHERE SHIP_DATE IS NULL;
SELECT COUNT(*) FROM FACT_ORDERS WHERE SHIP_MODE IS NULL;
SELECT COUNT(*) FROM FACT_ORDERS WHERE CUSTOMER_ID IS NULL;


IS THERE ANY CUSTOMER IN FACT_ORDER WHOS DATA IS NOT PRESENT IN CUSTOMER TABLE........

SELECT CUSTOMER_ID FROM FACT_ORDERS MINUS SELECT CUSTOMER_ID FROM DIM_CUSTOMERS;


IS THERE ANY PRODUCT PRESENT IN FACT_ITEMS WHOS DATA IS NOT PRESENT IN PRODUCT LIST......

SELECT PRODUCT_ID FROM FACT_ITEMS MINUS SELECT PRODUCT_ID FROM PRODUCTS;


_________________________FULL LOADING_____________________


SELECT * FROM ORDERS;
SELECT * FROM FACT_ORDERS;

SELECT COUNT(*) FROM ORDERS;
SELECT COUNT(*) FROM FACT_ORDERS;

TRUNCATE TABLE FACT_ORDERS;

COMMIT;


_________________INCREMENTAL LOADING__________________________________________


SELECT ORDER_ID FROM ITEMS ORDER BY ORDER_ID ASC;
SELECT MAX(ORDER_ID) FROM ITEMS;

SELECT * FROM ORDERS;
INSERT INTO ORDERS VALUES ('US-2018-900001','01-01-18','03-01-18','STANDARD CLASS','CG-12520');
COMMIT;

SELECT COUNT(*) FROM ORDERS WHERE ORDER_ID = 'US-2018-900001';

SELECT * FROM ORDERS where ORDER_ID = 'US-2018-900001';
SELECT * FROM FACT_ORDERS where ORDER_ID = 'US-2018-900001';
COMMIT;

SELECT COUNT(*) FROM ORDERS;
SELECT COUNT(*) FROM FACT_ORDERS;

TRUNCATE TABLE FACT_ORDERS;
COMMIT;

INSERT INTO ORDERS VALUES ('US-2018-900002','02-01-18','03-01-18','STANDARD CLASS','CG-12530');

______________________________________________________________

SELECT * FROM ITEMS;
SELECT MAX(ORDER_ID) FROM ITEMS;
SELECT COUNT(*) FROM FACT_ITEMS;