----------------------------TABLES-------------------------------------
------RAW--------
SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;

SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(*) FROM ORDERS;

SELECT COUNT(DISTINCT ORDER_ID) FROM ORDERS;
SELECT COUNT(DISTINCT ORDER_ID) FROM FACT_ORDERS;

SELECT COUNT(*) FROM ITEMS;
SELECT COUNT(*) FROM FACT_ITEMS;
TRUNCATE TABLE FACT_ITEMS;



DESC ITEMS;
-----CLEANED--------
SELECT * FROM DIM_CUSTOMERS;
SELECT * FROM DIM_PRODUCTS;
SELECT * FROM FACT_ORDERS;


SELECT COUNT(*) FROM DIM_CUSTOMERS;
SELECT COUNT(*) FROM DIM_PRODUCTS;
SELECT COUNT(*) FROM FACT_ORDERS;



RENAME CUSTOMERS TO CUSTOMER;

____________________________CUSTOMERS___________________________________

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR2(20),
    CUSTOMER_NAME VARCHAR2(100),
    SEGMENT VARCHAR2(30),
    COUNTRY VARCHAR2(50),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    POSTAL_CODE NUMBER,
    REGION VARCHAR2(30)
);

SELECT COUNT(*) FROM CUSTOMERS;
SELECT DISTINCT * FROM CUSTOMERS;
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM CUSTOMERS);


____________________________PRODUCTS______________________________________

CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR2(30),
    PRODUCT_NAME VARCHAR2(200),
    CATEGORY VARCHAR2(50),
    SUB_CATEGORY VARCHAR2(50)
);

SELECT COUNT(*) FROM PRODUCTS;
SELECT DISTINCT * FROM PRODUCTS;
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM PRODUCTS);


______________________________ORDERS_____________________________________

CREATE TABLE ORDERS (
    ORDER_ID VARCHAR2(30),
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SHIP_MODE VARCHAR2(30),
    CUSTOMER_ID VARCHAR2(20)
);

SELECT COUNT(*) FROM ORDERS;
SELECT DISTINCT * FROM ORDERS;
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM ORDERS);


___________________________ORDER_ITEMS___________________________________

CREATE TABLE ITEMS (
    ORDER_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(30),
    SALES NUMBER(10,2),
    QUANTITY NUMBER,
    DISCOUNT NUMBER(5,2),
    PROFIT NUMBER(10,2)
);

SELECT * FROM ITEMS;
SELECT DISTINCT * FROM ITEMS;
SELECT COUNT(*) FROM ITEMS;
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM ITEMS);
________________________________________________________________________

_________________________CLEANED TABLES__________________________________

CREATE TABLE DIM_CUSTOMERS AS SELECT DISTINCT * FROM CUSTOMERS;
SELECT * FROM DIM_CUSTOMERS;
SELECT COUNT(*) FROM DIM_CUSTOMERS;

CREATE TABLE DIM_PRODUCTS AS SELECT DISTINCT * FROM PRODUCTS;
SELECT * FROM DIM_PRODUCTS;
SELECT COUNT(*) FROM DIM_PRODUCTS;


CREATE TABLE FACT_ORDERS AS SELECT DISTINCT * FROM ORDERS;
SELECT * FROM FACT_ORDERS;
SELECT COUNT(*) FROM FACT_ORDERS;

COMMIT;

__CONSTRAINT

SELECT * FROM DIM_CUSTOMERS;
ALTER TABLE DIM_CUSTOMERS ADD CUST_KEY NUMBER;
UPDATE DIM_CUSTOMERS SET CUST_KEY = ROWNUM;
ALTER TABLE DIM_CUSTOMERS ADD CONSTRAINT PK_DIM_CUSTOMERS PRIMARY KEY (CUST_KEY);



SELECT * FROM DIM_PRODUCTS;
ALTER TABLE DIM_PRODUCTS ADD PROD_KEY NUMBER;
UPDATE DIM_PRODUCTS SET PROD_KEY = ROWNUM;
ALTER TABLE DIM_PRODUCTS ADD CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PROD_KEY);


SELECT * FROM FACT_ORDERS;
ALTER TABLE FACT_ORDERS ADD CONSTRAINT PK_FACT_ORDERS PRIMARY KEY (ORDER_ID);

_______________________________________________________________________________________________________
SCD TYPE 1:

SELECT * FROM CUSTOMER;
SELECT * FROM DIM_CUSTOMERS




_______________________________________________________________________________________________________
SCD TYPE 2:

;
SELECT * FROM CUSTOMER;
SELECT * FROM DIM_CUSTOMERS_TYPE2;

UPDATE CUSTOMER SET POSTAL_CODE = 40001 WHERE CUSTOMER_ID = 'CG-12520';
SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_ID = 'CG-12520';

SELECT * FROM CUSTOMER WHERE POSTAL_CODE = 40001;
SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE POSTAL_CODE = 40001;
SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_NAME = 'SALRO FLAG';
SELECT * FROM CUSTOMER WHERE CUSTOMER_NAME = 'SALRO FLAG';

SELECT * FROM (SELECT CUSTOMER_ID,COUNT(CUSTOMER_ID)C FROM DIM_CUSTOMERS_TYPE2 GROUP BY CUSTOMER_ID) WHERE C=1;


SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'AA-08080';
UPDATE CUSTOMER SET POSTAL_CODE = 40001 WHERE CUSTOMER_ID = 'AA-08080';

SELECT * FROM CUSTOMER  WHERE CUSTOMER_ID = 'AA-08080';

SELECT * FROM DIM_CUSTOMERS_TYPE2  WHERE CUSTOMER_ID = 'AA-08080';

INSERT INTO CUSTOMER VALUES ('AA-11111'	,'IRENE HALE',	'HOME OFFICE',	'US','A','S',			400022,'WEST');
SELECT * FROM CUSTOMER  WHERE CUSTOMER_ID = 'AA-11111';
SELECT * FROM DIM_CUSTOMERS_TYPE2  WHERE CUSTOMER_ID = 'AA-11111';

UPDATE CUSTOMER SET COUNTRY = 'UNITEDSTATES'  WHERE CUSTOMER_ID = 'AA-11111';

SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_ID = 'AA-11111';
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'AA-11111';


TRUNCATE TABLE DIM_CUSTOMERS_TYPE2;
SELECT * FROM DIM_CUSTOMERS_TYPE2;
UPDATE CUSTOMER SET REGION = 'EAST' WHERE CUSTOMER_NAME = 'SALRO FLAG';
SELECT * FROM CUSTOMER WHERE CUSTOMER_NAME = 'SALRO FLAG';
SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_NAME = 'SALRO FLAG';

SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_ID = 'A';


SELECT * FROM DIM_CUSTOMERS_TYPE2 WHERE CUSTOMER_ID = 'AA-0000';
UPDATE CUSTOMER SET CUSTOMER_NAME = 'REENA' WHERE CUSTOMER_ID = 'AA-0000';
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'AA-0000';


INSERT INTO CUSTOMER VALUES ('AA-0000'	,'IRENE HALE',	'HOME OFFICE',	'US','A','S',			400022,'WEST');


_____________________LOAD PRODUCTS_________________________

SELECT * FROM PRODUCTS WHERE SUB_CATEGORY = 'Chairs';
SELECT * FROM PRODUCTS WHERE SUB_CATEGORY = 'Cupboard';


SELECT * FROM DIM_PRODUCTS;
SELECT * FROM DIM_PRODUCTS WHERE SUB_CATEGORY = 'Chairs';
SELECT * FROM DIM_PRODUCTS WHERE SUB_CATEGORY = 'Cupboard';


UPDATE PRODUCTS SET SUB_CATEGORY = 'Chairs' WHERE SUB_CATEGORY = 'Cupboard';

SELECT COUNT(*) FROM DIM_PRODUCTS;
SELECT COUNT(*) FROM PRODUCTS;


COMMIT;


_____________________LOAD FACT ORDER TABLE_______________________

SELECT * FROM ORDERS;
SELECT * FROM FACT_ORDERS;


TRUNCATE TABLE FACT_ORDERS;

___________________FACT ITEMS_____________________


SELECT * FROM ITEMS;

CREATE TABLE FACT_ITEMS AS SELECT * FROM ITEMS WHERE 1=2;

SELECT * FROM FACT_ITEMS;












PRACTICE SCD TYPE 1__________________________________________________________________________________


RE-19405
JR-15700
LD-16855
AO-10810
CJ-11875

UPDATE CUSTOMERS SET CUSTOMER_NAME = 'ROHANNNNN' WHERE CUSTOMER_ID = 'RE-19405';

SELECT * FROM (SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID)C FROM DIM_CUSTOMERS GROUP BY CUSTOMER_ID) WHERE C=1;

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'RE-19405';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'RE-19405';

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'CG-12520';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'CG-12520';

UPDATE CUSTOMER SET CUSTOMER_NAME = 'SALRO FLAG' WHERE CUSTOMER_ID = 'CG-12520';

SELECT * FROM CUSTOMER;
SELECT * FROM DIM_CUSTOMERS;

SELECT * FROM (SELECT CUSTOMER_ID,COUNT(CUSTOMER_ID)C FROM CUSTOMER GROUP BY CUSTOMER_ID) WHERE C=1;

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'CJ-11875';

UPDATE CUSTOMER SET CUSTOMER_NAME = 'SALRO FLAG' WHERE CUSTOMER_ID = 'CJ-11875';

SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'CJ-11875';

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'AA-0000';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'AA-0000';


SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'CJ-11875';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'CJ-11875';



SELECT * FROM CUSTOMER WHERE CUSTOMER_NAME = 'SALRO FLAG';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_NAME = 'SALRO FLAG';

UPDATE CUSTOMER SET SEGMENT = 'HOME_OFFICE' WHERE CUSTOMER_ID = 'CG-12520' AND CUSTOMER_NAME = 'SALRO FLAG';

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'CG-12520' AND CUSTOMER_NAME = 'SALRO FLAG';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'CG-12520' AND CUSTOMER_NAME = 'SALRO FLAG';
CG-12520	SALRO FLAG	Consumer	United States	Houston	Texas	77070	Central	37

SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = 'AO-10810';
SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'AO-10810';

UPDATE CUSTOMER SET SEGMENT = 'HOME_OFFICE' WHERE CUSTOMER_ID = 'AO-10810';

SELECT * FROM DIM_CUSTOMERS WHERE CUSTOMER_ID = 'AA-08080';

________________SCD TYPE 2_________________________________________

SELECT * FROM CUST1;
SELECT * FROM DIM_CUST1;

CREATE TABLE DIM_CUST2 AS SELECT * FROM DIM_CUST1 WHERE 1=2;


SELECT * FROM DIM_CUST2;
ALTER TABLE DIM_CUST2 ADD VERSION INT;


________________-PRODUCTS_________________________

SELECT * FROM PRODUCTS;
SELECT * FROM DIM_PRODUCTS;

CREATE TABLE PRACT_PROD AS SELECT * FROM PRODUCTS WHERE 1=2;
CREATE TABLE DIM_PRACT_PROD AS SELECT * FROM DIM_PRODUCTS WHERE 1=2;

SELECT * FROM PRACT_PROD;
SELECT * FROM DIM_PRACT_PROD;




______________

SELECT * FROM ORDERS;
SELECT * FROM FACT_ORDERS;